all:
	xelatex learning-representations-by-back-propagating-errors.tex
	xelatex learning-representations-by-back-propagating-errors.tex

clean:
	-rm *.bcf
	-rm *.out
	-rm *.xml
	-rm *.aux
	-rm *.log
	-rm *.toc
